spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&charaterEncoding=utf-8
    username: root
    password: ekfkakqk4
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update